-- Automatically generated by build.lua, do not edit
return {
    require(script.Parent.DerivedCoreProperties1),
    require(script.Parent.DerivedCoreProperties2),
    require(script.Parent.DerivedCoreProperties3),
    require(script.Parent.DerivedCoreProperties4),
    require(script.Parent.DerivedCoreProperties5),
    require(script.Parent.DerivedCoreProperties6),
}
