-- Automatically generated by build.lua, do not edit
return {
    require(script.Parent.UnicodeData1),
    require(script.Parent.UnicodeData2),
    require(script.Parent.UnicodeData3),
    require(script.Parent.UnicodeData4),
    require(script.Parent.UnicodeData5),
    require(script.Parent.UnicodeData6),
    require(script.Parent.UnicodeData7),
    require(script.Parent.UnicodeData8),
    require(script.Parent.UnicodeData9),
    require(script.Parent.UnicodeData10),
}
